export default {
    // contactUs screen
    contactUS: "اتصل بنا",
    enote: 'أدخل ملاحظتك',
    noteHere: 'ملاحظتك هنا',
    Emailhere: 'البريد الإلكتروني هنا',
    enterEmail: 'أدخل بريدك الإلكتروني',
    nameHere: 'الاسم هنا',
    enterName: 'أدخل أسمك',
    note: 'إشعارات',
    phoneher: 'الهاتف هنا',
    // ,,,,,,,
    editaccount: 'تعديل البيانات الخاصة بي',
    changPass: 'تغيير كلمة المرور',
    save: 'حفظ',
    changepassSucc: 'تم تحديث كلمة المرور بنجاح',
    changepassSuccDesc: 'تم تغيير كلمة المرور الخاصة بك بنجاح.',
    changeDataSucc: 'التغييرات  تم حفظها بنجاح',
    changeDataSuccDesc: 'تم تغيير بياناتك بنجاح.',
    Currentpassword: 'كلمة المرور الحالية',
    Newpassword: 'كلمة المرور الجديدة',
    Re_enternewpassword: 'إعادة إدخال كلمة المرور',
    back: 'الرجوع',
    saveChanges: 'احفظ التغييرات',
    changlang: 'تغيير اللغة',
    welcometxt: 'مرحبا بكم في مكفي! \n انضم إلينا الآن',
    welcometxtDriver: ' مرحبا بكم في مكفي! \n  انضم إلينا الآن كسائق',
    welcometxtdreiverReq: "مرحبًا بك في مكفي! \n أرسل طلبًا للانضمام كسائق" ,

    Joinnow: 'انضم الان',
    donthaveaccount: 'ليس لديك حساب؟',
    asDriver: "انضم كسائق",
    asclient:'انضم كعميل',
    signup: "أفتح حساب الأن",
    Phonenumber: 'رقم التليفون',
    Signin: 'تسجيل الدخول',
    Forgetpassword: 'نسيت كلمة المرور',
    Passwordhere: 'كلمة المرور هنا',
    Username: 'اسم المستخدم',
    Phonenumber: 'رقم التليفون',
    Email: 'بريد إلكتروني',
    Passworhere: 'المرور هنا',
    Signup: 'اشتراك',
    search: 'بحث',
    hello: 'اهلا',
    readyfororder: 'جاهز للطلب؟',
    Ordernow: "اطلب الان",
    Ordereverything: 'اطلب كل شيء!',
    OrdernowDesc: 'اطلب الآن الوصف سيكون هنا.',
    Myaccount: 'حسابي',
    Myaddresses: 'عناويني',
    Aboutus: 'معلومات عنا',
    language: 'لغة',
    Termsconditions: " البنود و الظروف",
    Contactus: 'اتصل بنا',
    Shareapp: 'شارك التطبيق',
    Myaddress: 'عنواني',
    addnewadd: "أضف عنوان جديد",
    enterPhoneNumberOrEmail: 'من فضلك ادخل رقم الهاتف او البريد الالكتروني',
    enterPassword: 'من فضلك ادخل كلمه المرور',
    incorrectData: "من فضلك تأكد من الاميل او الباسورد",
    enterphone: 'من فضلك ادخل رقم الهاتف',
    notIdentical: 'كلمات المرور غير متطابقه',
    forgetPassDesc: 'نسيت كلمة المرور ؟\nلا تقلق',
    enteryourPassword: 'ادخل رقمك السري',
    Phonenumber: 'رقم التليفون',
    sendcode: 'ارسال الكود',
    enterotp: 'أدخل otp المرسلة إلى  البريد الالكتروني',
    activate: "تفعيل",
    tryAfter: 'حاول مرة أخرى بعد',
    tryAgain: 'أرسل OTP مرة أخرى',
    pleaseEnterOTP: 'من فضلك ادخل رقم الكود',
    commonQestion: "الاسئلة الشائعه",
    enterphone2: 'ادخل رقم الهاتف',
    logoutask: 'هل ترغب بالخروج؟',
    nostay: 'لا ، ابق هنا',
    noq: 'لا يوجد اسئله شائعه',
    addnewadd: 'أضف عنوان جديد',
    Address_name: 'اسم عنوان *',
    Area: 'منطقة *',
    City: 'مدينة *',
    Address: 'عنوان *',
    Phone_number: 'رقم التليفون *',
    Notes: 'ملحوظات',
    mainadd: 'العنوان الرئيسي',
    editadd: 'تعديل العنوان',
    edit: 'تعديل',
    AddressPlaceHolder: 'بلوك ، بناء ، طابق ، شقة ..',
    Delete_address: 'حذف العنوان',
    Delete_address_Desc: 'هل أنت متأكد أنك تريد حذف العنوان؟',
    logout: 'تسجيل خروج',
    noAddressAvailble: 'لا يوجد عناوين حاليا',
    home: 'بيت',
    work: 'عمل',
    other: 'اخري',
    type: "نوع",
    Showall: 'اظهار الكل',
    cat: "التصنيفات",
    delvto: 'يسلم إلى',
    Deliverhere: 'يسلم هنا',
    den: 'اطلب كل شيء الآن',
    Orderdetails: 'تفاصيل الطلب',
    itemsPlaceholder: '1 أدخل العنصر الأول هنا',
    addcomment: 'أضف تعليقات',
    Deliveryaddress: 'عنوان التسليم',
    Deliverfrom: 'تسليم من',
    cpl: 'اختر موقع الالتقاط',
    cdl: 'اختر موقع التسليم',
    Paymentmethod: 'طريقة الدفع ',
    Promocode: 'رمز ترويجي',
    Enterpromocode: 'إدخال الرمز الترويجي',
    done: 'تم',
    edc: 'تكلفة التسليم المقدرة',
    order: 'طلب',
    Pleasewait: 'انتظر من فضلك',
    waitfa: 'سيبدأ التسليم بعد قبول أحد فرساننا.',
    wfo: 'في انتظار العروض',
    aco: 'قبول العروض تلقائيًا',
    Disable: 'إبطال',
    Reject: 'يرفض',
    Accept: 'يقبل',
    enterbirth_date: "الرجاء تحديد تاريخ ميلادك",
    entergender: 'يرجى تحديد النوع',
    male: 'ذكر',
    female: 'انثي',
    birthdate: 'تاريخ الميلاد',
    newpassword:'كلمه المرور الجديده',
    somethingWrong:'يوجد خطأ ما',
    cart:'العربة',
    total:'المجموع',
    Sub_total:'المجموع الفرعي',
    VAT:'ضريبة القيمة المضافة',
    Checkout:'الدفع',
    Chooseaddress:'اختر العنوان',
    ana:'أضف عنوان جديد',
    gtp:"اذهب إلى الدفع",
    cpm:'اختر وسيلة الدفع',
    pay:'ادفع',
    Shippingaddress:'عنوان الشحن',
    Paymentmethod: 'طريقة الدفع او السداد',
    gender:'النوع',
    add:'اضافه',
    Send:'ارسال',
    fullname:'الاسم بالكامل',
    nationality:"الجنسيه",
    IDNumber:'رقم الهوية',
    nationalityID:'الرقم القومي',
    birthdate:"تاريخ الميلاد",
    carType:'نوع السياره',
    carnumbers:'ارقام السيارة',
    Numbers:'الارقام',
    letters:'الحروف',
    carPlate:'لوحة السيارة',
    next:'التالي',
    submit:'تأكيد',
    accTermsconditions:'أوافق على الشروط والأحكام',
    readIt:'اقرأها',
    Delivery:'توصيل',
    Pickup:'يلتقط',
    You:'أنت',
    Accountbalance:'رصيد الحساب',
    noo:'عدد الطلبات',
    Mywallet:'محفظتى',
    Result:'النتيجة',
    Status:'حالة',
    Processing:'يعالج',
    Preparing:'يجهز',
    Delivered:'تم التوصيل',
    Shipped:'تم الشحن',
    Deliverto: 'تسليم الى',
    pickupError:'من فضلك ادخل عنوان الالتقاط',
    deliverError:"من فضلك ادخل عنوان التوصيل",
    SAR:'ريال',
    cashondelivery:'الدفع عند الاستلام',
    Creditcard:'بطاقة إئتمان',
    pleaseEnterDetails:'من فضلك ادخل التفاصيل',
    close:'اغلاق',
    Remaining:'متبقي',
    Totalpaid:'مجموع المبالغ المدفوعة',
    Used:'مستخدم',
    topwallet:'من أعلى إلى المحفظة',
    Mytransactions:'معاملاتي',
    Chooseyourbank:'اختر البنك الذي تتعامل معه',
    Uploadyourphoto:'ارفع صورتك',
    UploadcivilID:'تحميل البطاقة المدنية',
    Uploadlicense:'رفع الرخصة',
    iban:'IBAN',
    enteryournationalty:'أدخل جنسيتك',
    enterIDNumber:'أدخل رقم الهوية',
    enternationality_id:'أدخل رقم الهوية',
    entercity:'أدخل المدينة',
    enterarea:'أدخل المنطقة',
    entercartype:'أدخل نوع السيارة',
    enterserial_plate_number:'أدخل رقم اللوحة التسلسلي',
    enterletter_plate_number:'أدخل رقم لوحة الحرف',
    enterplate_number:'أدخل رقم اللوحة',
    car_license:'رخصة السيارة',
    driving_license:'رخصة قيادة',
    entercar_license:'أدخل رخصة السيارة',
    enterdriving_license:'أدخل رخصة القيادة',
    enteriban:'أدخل رقم الحساب بصيغة IBAN',
    accountcreatsuccess:'تم انشاء الحساب بنجاح',
    connectWithAdmin:'من فضلك تواصل مع الادمن',
    chts:"انقر هنا لإرسال هذا الطلب للتسوق",
    Sendorder:'ارسال الطلب',
    CreatedDate:'تاريخ الإنشاء',
    Productsdetails:'تفاصيل الطلب',
    noorder:'لا يوجود طلب الان',
    gotowallet:'اذهب إلى المحفظة',
    Gotoorders:'اذهب إلى الطلبات',
    Upcomming:'القادمة',
    Previous:'السابق',
    pending:'قيد الانتظار',
    dt:'وقت التوصيل',
    price:"تكلفة التوصيل"

    



};
