export default {
        // contactUs screen
        contactUS: "Contact US",
        enote: 'Enter your note',
        noteHere: 'Note Here',
        Emailhere: 'Email here',
        enterEmail: 'Enter your email',
        nameHere: 'Name here',
        enterName: ' Enter your name',
        note: 'Notifications',
        // ..........
        editaccount: "Edit my data",
        changPass: 'Change password',
        save: 'Save',
        changepassSucc: 'Passowrd updated successfully',
        changepassSuccDesc: 'Your password has been changed successfully.',
        changeDataSuccDesc: 'Your data has been changed successfully.',
        changeDataSucc: 'Changes saved successfully',
        Currentpassword: 'Current password',
        Newpassword: 'New password',
        Re_enternewpassword: 'Re-enter new password',
        back: 'back',
        saveChanges: 'Save changes',
        changlang: 'Change language',
        welcometxt: "Welcome to makfy! \n Join us now",
        welcometxtDriver: "Welcome to makfy! \n Join us now as a driver",
        welcometxtdreiverReq: "Welcome to makfy! \n Send request to join as Driver",
        Joinnow: 'Join now',
        donthaveaccount: 'Don’t have account?',
        asDriver: 'Join as driver',
        asclient: "Join as client",
        signup: 'Sign up now',
        Phonenumber: 'Phone number',
        Signin: 'Sign in',
        Forgetpassword: 'Forget password',
        Passwordhere: 'Password here',
        Username: 'User name',
        Phonenumber: 'Phone number',
        Email: 'Email',
        Passworhere: 'Password here',
        Signup: 'Sign up',
        search: 'Search',
        hello: 'hello',
        readyfororder: "Ready to order?",
        Ordernow: ' Order now',
        Ordereverything: 'Order everything!',
        OrdernowDesc: 'Order now description will be here.',
        Myaccount: 'My account',
        Myaddresses: 'My addresses',
        Aboutus: 'About us',
        language: 'language',
        Termsconditions: "Terms & conditions",
        Contactus: 'Contact us',
        Shareapp: 'Share app',
        Myaddress: 'My address',
        addnewadd: 'Add new address',
        enterPhoneNumberOrEmail: 'Please enter Phone Number or Email',
        enterPassword: 'Please Enter Password',
        incorrectData: "Incorrect Data,Please try again with correct data",
        enterphone: 'Please enter Phone Number',
        notIdentical: 'Passwords do not match',
        forgetPassDesc: 'Forget your password? \n Don’t worry',
        enteryourPassword: 'Enter your password',
        Phonenumber: 'Phone number',
        sendcode: 'Send Code',
        enterotp: 'Enter otp sent to your Email',
        activate: 'Activate',
        tryAfter: 'Try again after',
        tryAgain: 'Send OTP again',
        pleaseEnterOTP: 'Please Enter OTP',
        commonQestion: 'FAQ',
        phoneher: 'phone her',
        enterphone2: 'Enter your phone number',
        logoutask: 'Do you want to log out?',
        nostay: 'No, stay here',
        noq: 'no common Qestion',
        addnewadd: 'Add new address',
        Address_name: 'Address name *',
        Area: 'Area *',
        City: 'City *',
        Address: 'Address *',
        Phone_number: 'Phone number *',
        Notes: 'Notes',
        mainadd: 'Main address',
        editadd: 'Edit address',
        edit: 'Edit',
        AddressPlaceHolder: 'Block, building, floor, flat..',
        Delete_address: 'Delete address',
        Delete_address_Desc: 'Are you sure you want to delete address?',
        logout: 'LOG OUT',
        noAddressAvailble: 'There Is No Address ',
        home: 'Home',
        work: 'Work',
        other: 'Other',
        type: 'Type',
        cat: 'Categories',
        Showall: 'Show all',
        delvto: 'deliver to',
        Deliverhere: 'Deliver here',
        den: 'Order everything now',
        Orderdetails: 'Order details',
        itemsPlaceholder: '1 input first item here',
        addcomment: 'add comments',
        Deliveryaddress: 'Delivery address',
        Deliverfrom: 'Deliver from',
        cpl: 'pickup location',
        cdl: 'delivery location',
        Paymentmethod: "Payment method",
        Promocode: "Promocode",
        Enterpromocode: "Enter promocode",
        done: 'Done',
        edc: 'Estimated Delivery Cost',
        order: 'order',
        Pleasewait: 'Please wait',
        waitfa: 'Delivery will start after you accept one of our riders.',
        wfo: "Waiting for offers",
        aco: 'Auto accept offers',
        Disable: 'Disable',
        Reject: 'Reject',
        Accept: 'Accept',
        enterbirth_date: "Please select your Birh Date",
        entergender: 'please select Gender',
        male: 'Male',
        female: 'Female',
        birthdate: "Birth Date",
        newpassword: 'New Password',
        somethingWrong: 'something Wrong',
        cart: 'Cart',
        total: 'Total',
        Sub_total: 'Sub-total',
        VAT: 'VAT',
        Checkout: 'Checkout',
        Chooseaddress: 'Choose address',
        ana: 'Add new address',
        gtp: "Go to payment",
        cpm: 'Choose payment method',
        pay: 'Pay',
        Shippingaddress: 'Shipping address',
        Paymentmethod: 'Payment method ',
        add: 'add',
        Send: "Send",
        fullname: 'Full Name',
        nationality: 'Nationality',
        IDNumber: 'ID Number',
        nationalityID: 'Nationality ID',
        birthdate: 'Birthdate',
        carType: 'Car Type',
        carnumbers: 'Car Numbers',
        Numbers: 'Numbers',
        letters: 'Letters',
        carPlate: 'Car Plate',
        next: 'Next',
        submit: 'Submit',
        accTermsconditions: 'I agree to Terms & Conditions',
        readIt: 'Read it',
        Delivery: 'Delivery',
        Pickup: 'Pick up',
        You: 'You',
        Accountbalance: 'Account balance',
        noo: 'Number of orders',
        Mywallet: 'My wallet',
        Result: 'Result',
        Status: 'Status',
        Processing: 'Processing',
        Preparing: 'Preparing',
        Delivered: 'Delivered',
        Shipped: 'Shipped',
        Deliverto: 'Deliver To',
        pickupError: 'Please enter pickup address',
        deliverError: "Please enter the delivery address.",
        SAR: 'SAR',
        cashondelivery: 'Cash on delivery',
        Creditcard: 'Credit card',
        pleaseEnterDetails: 'please Enter Details',
        close: 'close',
        Remaining: 'Remaining',
        Totalpaid: 'Total paid',
        Used: 'Used',
        topwallet: 'TOPUP TO WALLET',
        Mytransactions: 'My transactions',
        Chooseyourbank: 'Choose your bank',
        Uploadyourphoto: 'Upload your photo',
        UploadcivilID: 'Upload civil ID',
        Uploadlicense: 'Upload license',
        iban: 'IBAN',
        enteryournationalty: 'enter your nationalty',
        enterIDNumber: 'enter ID Number',
        enternationality_id: 'enter nationality id',
        entercity: 'enter city',
        enterarea: 'enter area',
        entercartype:'enter car type',
        enterserial_plate_number:'enter serial plate number',
        enterletter_plate_number:'enter letter plate number',
        enterplate_number:'enter plate number',
        car_license:'car license',
        driving_license:'driving license',
        entercar_license:'enter car license',
        enterdriving_license:'enter driving license',
        enteriban:'enter iban',
        accountcreatsuccess:"Account Created Successfully",
        connectWithAdmin:'Please Connect With Admin',
        chts:'Click here to send this order to shop',
        Sendorder:'Send order',
        CreatedDate:'Created Date',
        Productsdetails:'Products details',
        noorder:'no order availble',
        gotowallet:'go to wallet',
        Gotoorders:'Go to orders',
        Upcomming:'Upcomming',
        Previous:'Previous',
        pending:'pending',
        dt:'Delivery time',
        price:'delivery cost'



};
